repository: scienceos.github.io/scienceos
theme: jekyll-theme-architect
name: ScienceOS
title: ScienceOS
description: a distro with PhD in Biology
author: Menegidio, F.B.
author_email: fabiano.menegidio@biology.bio.br

show_downloads: true
